import type { DemoAnalysisFixture } from "./types";

export const demoAnalysis: DemoAnalysisFixture = {
  contract: {
    fileName: "Acme Cloud Services Agreement.pdf",
    contractType: "SaaS services agreement",
    reviewingRole: "Customer",
    effectiveDate: "2026-07-01",
    pageCount: 18,
    clauseCount: 42,
    analysisCompletedAt: "2026-07-17T10:30:00+05:30",
  },
  navItems: [
    { id: "overview", label: "Overview", count: 8 },
    { id: "clauses", label: "Clauses", count: 42 },
    { id: "obligations", label: "Obligations", count: 16 },
    { id: "risks", label: "Commercial risks", count: 5 },
    { id: "smells", label: "Contract smells", count: 3 },
    { id: "evidence", label: "Evidence links", count: 31 },
  ],
  metrics: [
    {
      id: "coverage",
      label: "Evidence coverage",
      value: "86%",
      detail: "31 linked excerpts",
      tone: "success",
    },
    {
      id: "confidence",
      label: "Extraction confidence",
      value: "0.82",
      detail: "hybrid parse",
      tone: "accent",
    },
    {
      id: "dependencies",
      label: "Critical dependencies",
      value: "7",
      detail: "payment and termination paths",
      tone: "warning",
    },
    {
      id: "findings",
      label: "Open findings",
      value: "5",
      detail: "2 high commercial risks",
      tone: "danger",
    },
  ],
  graph: {
    nodes: [
      {
        id: "contract",
        label: "Agreement",
        type: "CONTRACT",
        x: 82,
        y: 92,
        size: 52,
      },
      {
        id: "customer",
        label: "Customer",
        type: "PARTY",
        x: 226,
        y: 48,
        size: 40,
        inspectorId: "customer-party",
      },
      {
        id: "provider",
        label: "Provider",
        type: "PARTY",
        x: 226,
        y: 138,
        size: 40,
      },
      {
        id: "fees",
        label: "Fees",
        type: "CLAUSE",
        x: 392,
        y: 48,
        size: 44,
        inspectorId: "fees-clause",
      },
      {
        id: "payment-obligation",
        label: "Payment",
        type: "OBLIGATION",
        x: 554,
        y: 48,
        size: 42,
        inspectorId: "payment-obligation",
      },
      {
        id: "termination",
        label: "Termination",
        type: "CLAUSE",
        x: 392,
        y: 142,
        size: 46,
        inspectorId: "termination-clause",
      },
      {
        id: "cure-period",
        label: "Cure period",
        type: "CONDITION",
        x: 554,
        y: 142,
        size: 40,
        inspectorId: "cure-condition",
      },
      {
        id: "service-credit",
        label: "Service credit",
        type: "RIGHT",
        x: 392,
        y: 238,
        size: 42,
        inspectorId: "service-credit-right",
      },
      {
        id: "liability-cap",
        label: "Liability cap",
        type: "CLAUSE",
        x: 554,
        y: 238,
        size: 46,
        inspectorId: "liability-cap",
      },
      {
        id: "cap-risk",
        label: "Cap mismatch",
        type: "FINDING",
        x: 706,
        y: 238,
        size: 44,
        inspectorId: "cap-risk",
      },
    ],
    edges: [
      {
        id: "contract-customer",
        source: "contract",
        target: "customer",
        type: "MENTIONS_PARTY",
        confidence: 0.94,
        pathType: "reference",
      },
      {
        id: "contract-provider",
        source: "contract",
        target: "provider",
        type: "MENTIONS_PARTY",
        confidence: 0.94,
        pathType: "reference",
      },
      {
        id: "contract-fees",
        source: "contract",
        target: "fees",
        type: "CONTAINS",
        confidence: 0.91,
        pathType: "dependency",
      },
      {
        id: "fees-payment",
        source: "fees",
        target: "payment-obligation",
        type: "ASSIGNED_TO",
        confidence: 0.86,
        pathType: "dependency",
      },
      {
        id: "payment-customer",
        source: "payment-obligation",
        target: "customer",
        type: "ASSIGNED_TO",
        confidence: 0.83,
        pathType: "dependency",
      },
      {
        id: "contract-termination",
        source: "contract",
        target: "termination",
        type: "CONTAINS",
        confidence: 0.9,
        pathType: "dependency",
      },
      {
        id: "termination-cure",
        source: "termination",
        target: "cure-period",
        type: "TRIGGERED_BY",
        confidence: 0.8,
        pathType: "dependency",
      },
      {
        id: "termination-payment",
        source: "payment-obligation",
        target: "termination",
        type: "DEPENDS_ON",
        confidence: 0.78,
        pathType: "risk",
        dashed: true,
      },
      {
        id: "service-liability",
        source: "service-credit",
        target: "liability-cap",
        type: "AFFECTS",
        confidence: 0.76,
        pathType: "reference",
        dashed: true,
      },
      {
        id: "liability-finding",
        source: "liability-cap",
        target: "cap-risk",
        type: "SUPPORTED_BY",
        confidence: 0.81,
        pathType: "risk",
      },
    ],
  },
  defaultInspectorId: "liability-cap",
  inspectors: [
    {
      id: "liability-cap",
      nodeId: "liability-cap",
      clauseRef: "Section 11.2",
      title: "Aggregate liability cap",
      nodeType: "CLAUSE",
      severity: "HIGH",
      confidence: 0.81,
      labels: ["COMMERCIAL_RISK", "UNCERTAIN"],
      summary:
        "The cap appears to include service credits while excluding several provider obligations. This is a commercial review signal, not a legal conclusion.",
      keyInfo: [
        { label: "Role reviewed", value: "Customer" },
        { label: "Linked finding", value: "Cap mismatch" },
        { label: "Evidence status", value: "Partially verified" },
      ],
      dependencyChain: [
        {
          id: "dep-service-credit",
          label: "Service credit remedy",
          relationship: "May consume available cap",
          severity: "MEDIUM",
        },
        {
          id: "dep-indemnity",
          label: "IP indemnity",
          relationship: "Listed outside cap in one clause",
          severity: "INFO",
        },
      ],
      evidence: [
        {
          id: "ev-cap-1",
          clauseRef: "11.2",
          page: 14,
          excerpt:
            "aggregate liability will not exceed fees paid in the six months before the claim",
          validationStatus: "PARTIALLY_VERIFIED",
        },
      ],
      commercialImpact:
        "The customer may have limited recovery for outages if credits and damages draw from the same pool.",
      uncertainty:
        "Governing law and negotiated exhibits are not included in this static sample.",
      suggestedAction:
        "Consider separating service credits from the liability cap or adding a targeted carveout for uptime failures.",
      history: [
        { label: "Detected", detail: "Linked from liability and service level clauses" },
        { label: "Validation", detail: "Needs reviewer confirmation" },
      ],
    },
    {
      id: "fees-clause",
      nodeId: "fees",
      clauseRef: "Section 4.1",
      title: "Fees and payment timing",
      nodeType: "CLAUSE",
      severity: "MEDIUM",
      confidence: 0.84,
      labels: ["STRUCTURAL_DIAGNOSTIC", "COMMERCIAL_RISK"],
      summary:
        "Payment timing is explicit, but the late fee cross-reference depends on a separate termination remedy.",
      keyInfo: [
        { label: "Due date", value: "30 days from invoice" },
        { label: "Actor", value: "Customer" },
        { label: "Evidence status", value: "Verified" },
      ],
      dependencyChain: [
        {
          id: "dep-payment-termination",
          label: "Termination for non-payment",
          relationship: "Depends on notice and cure",
          severity: "MEDIUM",
        },
      ],
      evidence: [
        {
          id: "ev-fees-1",
          clauseRef: "4.1",
          page: 6,
          excerpt: "Customer will pay undisputed invoices within thirty days",
          validationStatus: "VERIFIED",
        },
      ],
      commercialImpact:
        "Cash-flow exposure is bounded by invoice disputes, but suspension timing should be checked.",
      uncertainty:
        "The sample does not include order forms that may override fee timing.",
      suggestedAction:
        "Confirm whether disputed invoice procedures pause suspension and late fees.",
      history: [
        { label: "Detected", detail: "Parsed as payment obligation" },
        { label: "Validation", detail: "Evidence matched source excerpt" },
      ],
    },
    {
      id: "termination-clause",
      nodeId: "termination",
      clauseRef: "Section 9.3",
      title: "Termination for uncured breach",
      nodeType: "CLAUSE",
      severity: "MEDIUM",
      confidence: 0.8,
      labels: ["CONTRACT_SMELL", "NEGOTIATION_SUGGESTION"],
      summary:
        "The breach cure path is clear, but suspension and termination remedies are spread across separate sections.",
      keyInfo: [
        { label: "Cure period", value: "15 days" },
        { label: "Trigger", value: "Material breach" },
        { label: "Evidence status", value: "Verified" },
      ],
      dependencyChain: [
        {
          id: "dep-cure-period",
          label: "Cure period condition",
          relationship: "Triggers termination right",
          severity: "LOW",
        },
      ],
      evidence: [
        {
          id: "ev-term-1",
          clauseRef: "9.3",
          page: 12,
          excerpt: "may terminate if breach remains uncured after written notice",
          validationStatus: "VERIFIED",
        },
      ],
      commercialImpact:
        "Operational teams need notice tracking before exercising termination rights.",
      uncertainty:
        "Materiality is not defined in this static sample.",
      suggestedAction:
        "Consider consolidating cure, suspension, and termination references in one review note.",
      history: [
        { label: "Detected", detail: "Referenced by payment path" },
        { label: "Validation", detail: "Cross-reference needs review" },
      ],
    },
  ],
  executiveSummary: [
    "The sample agreement has strong clause structure and most key obligations are linked to evidence.",
    "Commercial review should prioritize liability cap scope, termination dependencies, and service credit treatment.",
    "No jurisdiction-specific legal enforceability assessment is included in this visual fixture.",
  ],
  topFindings: [
    {
      id: "finding-cap",
      title: "Liability cap may absorb service credits",
      category: "COMMERCIAL_RISK",
      severity: "HIGH",
      summary:
        "Service credits and damages appear connected to the same recovery limit.",
      clauseRefs: ["7.4", "11.2"],
      confidence: 0.81,
    },
    {
      id: "finding-cure",
      title: "Termination path depends on separate cure language",
      category: "CONTRACT_SMELL",
      severity: "MEDIUM",
      summary:
        "The remedy can be traced, but the path crosses payment, notice, and breach sections.",
      clauseRefs: ["4.1", "9.3"],
      confidence: 0.8,
    },
    {
      id: "finding-context",
      title: "Governing law missing from sample metadata",
      category: "UNCERTAIN",
      severity: "LOW",
      summary:
        "The fixture does not include jurisdiction context for legal-review checks.",
      clauseRefs: ["Metadata"],
      confidence: 0.72,
    },
  ],
};
